font_family Jetbrains Mono
font_size 11.3
enable_audio_bell no
tab_bar_edge top
term xterm-256color
editor nvim
window_margin_width 1
enabled_layouts tall, grid, fat
inactive_border_color #888888
active_border_color #888888
hide_window_decorations yes

map ctrl+shift+n new_window_with_cwd
map alt+right next_window
map alt+left previous_window

include gruvbox.conf
